import './reset.less'

import '@idux/components/_private/overlay/style/themes/seer.less'
import '@idux/components/button/style/themes/seer.less'
import '@idux/components/space/style/themes/seer.less'
import '@idux/components/radio/style/themes/seer.less'
import '@idux/components/tooltip/style/themes/seer.less'
import '@idux/components/message/style/themes/seer.less'
import '@idux/components/tabs/style/themes/seer.less'
import '@idux/components/icon/style/themes/seer.less'
import '@idux/components/anchor/style/themes/seer.less'
import '@idux/components/affix/style/themes/seer.less'
import '@idux/archive-vite-markdown-plugin/style/themes/seer.css'

import '@idux/components/style/core/reset-scroll.seer.css'
import '@idux/components/menu/style/themes/seer.less'
import '@idux/components/layout/style/themes/seer.less'
import '@idux/pro/layout/style/themes/seer.less'
import '@idux/cdk/index.css'

import './variables.less'
import '../page/variables.less'
import '../../../app.less'
import '../../../page.less'
import '../../../demo.less'
import '../page/overwrite.less'
import './overwrite.less'
