import '@idux/components/style/core/reset.seer.css'
import '@idux/components/style/core/reset-scroll.seer.css'
import '@idux/components/seer.less'
import '@idux/cdk/index.css'
import '@idux/archive-markdown-plugin/style/themes/seer.css'

import '../page/variables.less'
import './variables.less'
import '../../../app.less'
import '../../../page.less'
import '../../../demo.less'